// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbarlmruuuxldcxabutt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiYXJsbXJ1dXV4bGRjeGFidXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODY2MzcsImV4cCI6MjA2NzQ2MjYzN30.yPhyPinoSGYjG8VOem2Rnc8RXUtX17hvLuQ5ThduHIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});